package hotel.main.mkodo;

import java.awt.TextArea;
import javax.swing.JTextArea;

public class MainFrame extends javax.swing.JFrame {

    private HotelSystem hotelSystem;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        hotelSystem = new HotelSystem(viewPanel);
        hotelSystem.start();
    }

    public JTextArea getRoomNumberTextArea() {
        return roomNumberTextArea;
    }

    public JTextArea getTimeTextArea() {
        return timeTextArea;
    }

    public JTextArea getViewPanel() {
        return viewPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setAlarmButton = new javax.swing.JButton();
        cancelAlarmButton = new javax.swing.JButton();
        nextAlarmCallButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewPanel = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        roomNumberTextArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        timeTextArea = new javax.swing.JTextArea();
        timeLabel = new javax.swing.JLabel();
        roomNumberLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        setAlarmButton.setText("Set Alarm");
        setAlarmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setAlarmButtonActionPerformed(evt);
            }
        });

        cancelAlarmButton.setText("Cancel Alarm");
        cancelAlarmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelAlarmButtonActionPerformed(evt);
            }
        });

        nextAlarmCallButton.setText("Next Alarm Call");
        nextAlarmCallButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextAlarmCallButtonMouseClicked(evt);
            }
        });
        nextAlarmCallButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextAlarmCallButtonActionPerformed(evt);
            }
        });

        viewPanel.setEditable(false);
        viewPanel.setColumns(20);
        viewPanel.setRows(5);
        viewPanel.setAutoscrolls(false);
        jScrollPane1.setViewportView(viewPanel);

        roomNumberTextArea.setColumns(20);
        roomNumberTextArea.setRows(5);
        jScrollPane2.setViewportView(roomNumberTextArea);

        timeTextArea.setColumns(20);
        timeTextArea.setRows(5);
        jScrollPane3.setViewportView(timeTextArea);

        timeLabel.setText("Time:");

        roomNumberLabel.setText("Room Number:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(cancelAlarmButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(setAlarmButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nextAlarmCallButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(roomNumberLabel)
                                        .addGap(101, 101, 101)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(timeLabel)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(4, 4, 4)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancelAlarmButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nextAlarmCallButton)
                        .addComponent(setAlarmButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeLabel)
                    .addComponent(roomNumberLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setAlarmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setAlarmButtonActionPerformed
        if (roomNumberTextArea.getText().equals("")) {
            viewPanel.setText("Please enter a room number.");
        } else if (timeTextArea.getText().equals("")) {
            viewPanel.setText("Please enter an alarm time.");
        } else {
            int roomNumber = Integer.parseInt(roomNumberTextArea.getText());
            String time = timeTextArea.getText();
            hotelSystem.setAlarmTime(roomNumber, time);
            viewPanel.setText("Alarm set for room number: " + roomNumber + " at: " + time);
            timeTextArea.setText("");
            roomNumberTextArea.setText("");
        }
    }//GEN-LAST:event_setAlarmButtonActionPerformed

    private void nextAlarmCallButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextAlarmCallButtonMouseClicked

    }//GEN-LAST:event_nextAlarmCallButtonMouseClicked

    private void nextAlarmCallButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextAlarmCallButtonActionPerformed
        viewPanel.setText(hotelSystem.getNextCallRequest());
    }//GEN-LAST:event_nextAlarmCallButtonActionPerformed

    private void cancelAlarmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelAlarmButtonActionPerformed
        if (roomNumberTextArea.getText().equals("")) {
            viewPanel.setText("Please enter the room number in below.");
        } else {
            hotelSystem.cancelAlarm(Integer.parseInt(roomNumberTextArea.getText()));
            roomNumberTextArea.setText("");
        }
    }//GEN-LAST:event_cancelAlarmButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelAlarmButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton nextAlarmCallButton;
    private javax.swing.JLabel roomNumberLabel;
    private javax.swing.JTextArea roomNumberTextArea;
    private javax.swing.JButton setAlarmButton;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JTextArea timeTextArea;
    private javax.swing.JTextArea viewPanel;
    // End of variables declaration//GEN-END:variables
}
