package hotel.main.mkodo;

public class MainFrame extends javax.swing.JFrame {

    private final HotelSystem hotelSystem;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        hotelSystem = new HotelSystem(viewPanel);
        hotelSystem.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setAlarmButton = new javax.swing.JButton();
        cancelAlarmButton = new javax.swing.JButton();
        nextAlarmCallButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewPanel = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        roomNumberTextArea = new javax.swing.JTextArea();
        timeLabel = new javax.swing.JLabel();
        roomNumberLabel = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        hoursTextArea = new javax.swing.JTextArea();
        timeLabel1 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        minutesTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        setAlarmButton.setText("Set Alarm");
        setAlarmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setAlarmButtonActionPerformed(evt);
            }
        });

        cancelAlarmButton.setText("Cancel Alarm");
        cancelAlarmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelAlarmButtonActionPerformed(evt);
            }
        });

        nextAlarmCallButton.setText("Next Alarm Call");
        nextAlarmCallButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextAlarmCallButtonMouseClicked(evt);
            }
        });
        nextAlarmCallButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextAlarmCallButtonActionPerformed(evt);
            }
        });

        viewPanel.setEditable(false);
        viewPanel.setColumns(20);
        viewPanel.setLineWrap(true);
        viewPanel.setRows(5);
        viewPanel.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(viewPanel);

        roomNumberTextArea.setColumns(20);
        roomNumberTextArea.setRows(5);
        jScrollPane2.setViewportView(roomNumberTextArea);
        minutesTextArea.setLineWrap(true);

        timeLabel.setText("Hours:");

        roomNumberLabel.setText("Room Number:");

        hoursTextArea.setColumns(20);
        hoursTextArea.setRows(1);
        hoursTextArea.setWrapStyleWord(true);
        jScrollPane4.setViewportView(hoursTextArea);
        hoursTextArea.setLineWrap(true);

        timeLabel1.setText("Minutes:");

        minutesTextArea.setColumns(20);
        minutesTextArea.setRows(5);
        minutesTextArea.setWrapStyleWord(true);
        jScrollPane5.setViewportView(minutesTextArea);
        minutesTextArea.setLineWrap(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelAlarmButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(setAlarmButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nextAlarmCallButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(roomNumberLabel)
                                .addGap(101, 101, 101)))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(timeLabel)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(timeLabel1))))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancelAlarmButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nextAlarmCallButton)
                        .addComponent(setAlarmButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeLabel)
                    .addComponent(roomNumberLabel)
                    .addComponent(timeLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setAlarmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setAlarmButtonActionPerformed
        if (roomNumberTextArea.getText().equals("")) {
            viewPanel.append("Please enter a room number.\n");
        } else if (hoursTextArea.getText().equals("") || minutesTextArea.getText().equals("")) {
            viewPanel.append("Please enter an alarm time.\n");
        } else {
            if (Integer.parseInt(minutesTextArea.getText()) % 5 == 0) {
                int roomNumber = Integer.parseInt(roomNumberTextArea.getText());
                String time = hoursTextArea.getText() + ":" + minutesTextArea.getText() + ":00";
                hotelSystem.setAlarmTime(roomNumber, time);
                viewPanel.append("Alarm set for room number: " + roomNumber + " at: " + time + "\n");
                hoursTextArea.setText("");
                minutesTextArea.setText("");
                roomNumberTextArea.setText("");
            } else {
                viewPanel.append("Please ensure you enter minutes as a multiple of 5.\n");
            }
        }
    }//GEN-LAST:event_setAlarmButtonActionPerformed

    private void nextAlarmCallButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextAlarmCallButtonMouseClicked

    }//GEN-LAST:event_nextAlarmCallButtonMouseClicked

    private void nextAlarmCallButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextAlarmCallButtonActionPerformed
        viewPanel.append(hotelSystem.getNextCallRequest() + "\n");
    }//GEN-LAST:event_nextAlarmCallButtonActionPerformed

    private void cancelAlarmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelAlarmButtonActionPerformed
        if (roomNumberTextArea.getText().equals("")) {
            viewPanel.append("Please enter the room number in below.\n");
        } else {
            hotelSystem.cancelAlarm(Integer.parseInt(roomNumberTextArea.getText()));
            roomNumberTextArea.setText("");
        }
    }//GEN-LAST:event_cancelAlarmButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelAlarmButton;
    private javax.swing.JTextArea hoursTextArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea minutesTextArea;
    private javax.swing.JButton nextAlarmCallButton;
    private javax.swing.JLabel roomNumberLabel;
    private javax.swing.JTextArea roomNumberTextArea;
    private javax.swing.JButton setAlarmButton;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JLabel timeLabel1;
    private javax.swing.JTextArea viewPanel;
    // End of variables declaration//GEN-END:variables
}
